version: 0.1

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 695868544757.dkr.ecr.eu-west-1.amazonaws.com
      - REPOSITORY_URI=695868544757.dkr.ecr.eu-west-1.amazonaws.com/cicdlab
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD-ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on 'date'
      - echo Building the Docker image...
      - docker build -t cicdlab . 
      - docker tag cicdlab:latest 695868544757.dkr.ecr.eu-west-1.amazonaws.com/cicdlab:latest
  post_build:
    commands:
      - echo Build completed on 'date'
      - echo Pushing the Docker images...
      - docker push 695868544757.dkr.ecr.eu-west-1.amazonaws.com/cicdlab:latest
      - echo Writing image definitions file...
      - printf '[{"name":"app","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json
