version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 695868544757.dkr.ecr.eu-west-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t 695868544757.dkr.ecr.eu-west-1.amazonaws.com/cicdlab:latest .
      - docker tag 695868544757.dkr.ecr.eu-west-1.amazonaws.com/cicdlab:latest 695868544757.dkr.ecr.eu-west-1.amazonaws.com/cicdlab:latest     
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 695868544757.dkr.ecr.eu-west-1.amazonaws.com/cicdlab:latest
      - printf '[{"name":"cicdlab","imageUri":"%s"}]' 695868544757.dkr.ecr.eu-west-1.amazonaws.com/cicdlab:latest > imagedefinitions.json
      - cat imagedefinitions.json 
artifacts:
    files: 
      - imagedefinitions.json
