...
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/h5o5x0i9
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t cicdlab:latest .
      - docker tag cicdlabp:latest public.ecr.aws/h5o5x0i9/cicdlabp:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push public.ecr.aws/h5o5x0i9/cicdlabp:latest
...
